using Tyuiu.ShakhovDK.Sprint3.Task1.V4.Lib;
DataService ds = new DataService();
int startValue, stopValue;
startValue = 1;
stopValue = 10;
double res;
Console.Title = "Спринт #3 | Выполнил: Шахов Д.К | ИИПБ-24-2";
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* Спринт #3                                                                              *");
Console.WriteLine("* Тема: Оператор цикла while                                                              *");
Console.WriteLine("* Задание #0                                                                             *");
Console.WriteLine("* Вариант #12                                                                            *");
Console.WriteLine("* Выполнил: Шахов Даниил Константинович | ИИПБ-24-2                                      *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                               *");
Console.WriteLine("* Написать программу используя цикл while, которая вычисляет сумму ряда по формуле       *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                                       *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine($" k_0 = {startValue}                                                                      ");
Console.WriteLine($" k_k = {stopValue}                                                                       ");
res = ds.GetSumSeries(startValue, stopValue);
Console.WriteLine("******************************************************************************************");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                                             *");
Console.WriteLine($"S = {res}");
Console.WriteLine("******************************************************************************************");
Console.ReadKey();