using Tyuiu.ShakhovDK.Sprint3.Task5.V18.Lib;
DataService ds = new DataService();
int x = 5;
int startValue1 = 1;
int stopValue1 = 3;
int startValue2 = 1;
int stopValue2 = 11;
double res = ds.GetSumSumSeries(x, startValue1, startValue2, stopValue1, stopValue2);
Console.Title = "Спринт #3 | Выполнил: Шахов Д.К | ИИПБ-24-2";
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* Спринт #3                                                                              *");
Console.WriteLine("* Тема: Вложенные циклы                                                                  *");
Console.WriteLine("* Задание #5                                                                             *");
Console.WriteLine("* Вариант #18                                                                            *");
Console.WriteLine("* Выполнил: Шахов Даниил Константинович | ИИПБ-24-2                                      *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                               *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                                       *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine($" Старт шага первой суммы ряда = {startValue1}");
Console.WriteLine($" Конец шага первой суммы ряда = {stopValue1}");
Console.WriteLine($" Старт шага второй суммы ряда = {startValue2}");
Console.WriteLine($" Конец шага второй суммы ряда = {stopValue2}");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                                             *");
Console.WriteLine($"y = {res}");
Console.WriteLine("******************************************************************************************");
Console.ReadKey();