using Tyuiu.ShakhovDK.Sprint3.Task3.V21.Lib;
DataService ds = new DataService();
string str = "f3g5ht g4j 34kg4", res;
char item = 'e';
Console.Title = "Спринт #3 | Выполнил: Шахов Д.К | ИИПБ-24-2";
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* Спринт #3                                                                              *");
Console.WriteLine("* Тема: Оператор цикла foreach                                                           *");
Console.WriteLine("* Задание #3                                                                             *");
Console.WriteLine("* Вариант #21                                                                            *");
Console.WriteLine("* Выполнил: Шахов Даниил Константинович | ИИПБ-24-2                                      *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                               *");
Console.WriteLine("Используя цикл foreach заменить цифры на букву e в строке: f3g5ht g4j 34kg4");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                                       *");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* f3g5ht g4j 34kg4                                                                       *");
res = ds.ReplaceNumOnChar(str, item);
Console.WriteLine("******************************************************************************************");
Console.WriteLine("******************************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                                             *");
Console.WriteLine(res);
Console.WriteLine("******************************************************************************************");
Console.ReadKey();